### ISSUE TITLE
about python

### ISSUE THREAD

**Issue by 34bit23** [vtcbca/basic-programming-34bit23#2]

**Comment by 34bit23** [comment]
what is python

**Comment by 22bit2** [comment]
python is high level programming language

**Comment by 34bit23** [comment]
ok but it was how to work

**Comment by 22bit2** [comment]
i have some small knowladge about python

**Comment by 34bit23** [comment]
ok no problam but you can explain you have know

**Comment by 22bit2** [comment]
why not sure

**Comment by 34bit23** [comment]
thank u plz explain

**Comment by 22bit2** [comment]
ok python is a high level language it was use  in turbo c++

**Comment by 34bit23** [comment]
programmer was love with python because increase productvity its provide

**Comment by 22bit2** [comment]
> programmer was love with python because increase productvity its provide

yes

**Comment by 22bit2** [comment]
because the edit-test-debug cycle is incredibly fast

**Comment by 34bit23** [comment]
ok but it was very deficult

**Comment by 22bit2** [comment]
yes i have also unlable for python 
i am also slow in  python

**Comment by 34bit23** [comment]
you are slow but i have no knowladge about python ??????

**Comment by 22bit2** [comment]
ok i am exchange some information with you you got undrstand????

**Comment by 34bit23** [comment]
yes

**Comment by 22bit2** [comment]
ok  next time you gain other information about python you can explain me ok

**Comment by 34bit23** [comment]
why not sure

**Comment by 22bit2** [comment]
ok bro meet next time

**Comment by 34bit23** [comment]
ok
